### ISSUE TITLE
Error w share on iPad using chrome

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/fly-django#112] opened 2016-03-25 15:38 UTC
Summary
This happened when trying to share the first badge
Is this a css error?

![image](https://cloud.githubusercontent.com/assets/7537946/14047415/1a100190-f27e-11e5-9c69-7a77c8361173.png)

**Comment by bartmika** [comment] 2016-03-25 16:05
No, this is not an error, this ticket is a duplicate of #86. @viralrain  needs to apply CSS/JS beautifucation because right now there is none.

**Comment by rodolfomartinez** [comment] 2016-10-14 19:48
@bartmika if necessary can we implement some basic CSS and/or get Kanwar involved?

**Comment by bartmika** [comment] 2016-10-15 19:27
This is not an error. This is the share page.

**Closed by bartmika** 2016-10-15 19:27 UTC
Labels: bug, duplicate
